apiVersion: v2
name: azure-pvc
version: 1.0.0
description: Create a persistent volume claim using a specified storage class name.
type: application
appVersion: "1.0"
maintainers:
  - name: Kevin Dietz
    email: info@opensquiggly.com
    url: https://opensquiggly.com