apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns-sa
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.14.0
        args:
        - --source=service
        - --source=ingress
        - --domain-filter={{ .Values.domanFilter }}
        - --provider={{ .Values.provider }}
        - --azure-resource-group={{ .Values.azureResourceGroup }}
        - --txt-owner-id={{ .Values.txtOwnerId }}
        volumeMounts:
        - name: azure-config-file
          mountPath: /etc/kubernetes
          readOnly: true
      volumes:
      - name: azure-config-file
        secret:
          secretName: {{ .Values.secretName }}