apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-dns-role
rules:
  - apiGroups: [ "" ]
    resources: [ "services", "endpoints", "pods" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "extensions", "networking.k8s.io" ]
    resources: [ "ingresses" ]
    verbs: [ "get", "watch", "list" ]