apiVersion: storage.k8s.io/v1
kind: StorageClass
allowVolumeExpansion: true
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
  name: {{ .Values.name }}
parameters:
  skuname: {{ .Values.skuname }}
provisioner: {{ .Values.provisioner }}
reclaimPolicy: {{ .Values.reclaimPolicy }}
volumeBindingMode: WaitForFirstConsumer