{{- if eq .Values.exposeWith "LoadBalancer" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  {{- if ne .Values.dnsHostName "" }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.dnsHostName }}   
  {{- end }}
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: {{ .Release.Name }}
{{- end -}}