apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Release.Name }}-pvc
spec:
  accessModes:
  - ReadWriteOnce
  {{- if ne .Values.useExistingPv "" }}
  {{- if ne .Values.existingPvStorageClass "" }}
  storageClassName: {{ .Values.existingPvStorageClass }}
  {{- else if ne .Values.useExistingStorageClass "" }}
  storageClassName: {{ .Values.useExistingStorageClass }}
  {{- else }}
  storageClassName: {{ .Release.Name }}-storageclass
  {{- end }}
  resources:
    requests:
      storage: 1Gi
  volumeName: {{ .Values.useExistingPv }}
  {{- else -}}
  {{- if ne .Values.useExistingStorageClass "" }}
  storageClassName: {{ .Values.useExistingStorageClass }}
  {{- else }}
  storageClassName: {{ .Release.Name }}-storageclass
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.diskSize }}Gi
  {{- end }}
  volumeMode: Filesystem