{{- if eq .Values.useExistingPvc "" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Release.Name }}-pvc
spec:
  accessModes:
  - ReadWriteOnce
  {{- if ne .Values.useExistingPv "" }}
  volumeName: {{ .Values.useExistingPv }}
  {{- else -}}
  {{- if ne .Values.useExistingStorageClass "" }}
  storageClassName: {{ .Values.useExistingStorageClass }}
  {{- else }}
  storageClassName: {{ .Release.Name }}-storageclass
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.diskSize }}Gi
  volumeMode: Filesystem
{{- end -}}  