apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Release.Name }}-pvc
spec:
  accessModes:
  - ReadWriteOnce
  {{- if eq .Values.useExistingStorageClass "" }}
  storageClassName: {{ .Release.Name }}-storageclass
  {{- else }}
  storageClassName: {{ .Values.useExistingStorageClass }}
  {{- end }}
  {{- if eq .Values.useExistingPv "" }}
  resources:
    requests:
      storage: {{ .Values.diskSize }}Gi
  {{- else }}
  resources:
    requests:
      storage: 1Gi
  volumeName: {{ .Values.useExistingPv }}
  {{- end }}
  volumeMode: Filesystem