apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Release.Name }}-azure-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Release.Name }}-managed-csi-premium-retain
  resources:
    requests:
      storage: {{ .Values.diskSize }}Gi  
  volumeMode: Filesystem  