apiVersion: storage.k8s.io/v1
kind: StorageClass
allowVolumeExpansion: true
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
  name: {{ .Release.Name }}-storageclass
parameters:
  skuname: {{ .Values.skuname }}
provisioner: {{ .Values.storageClassProvisioner }}
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer