apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Release.Name }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
#   resources:
#     requests:
#       storage: 30Gi  
  volumeMode: Filesystem 