apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}               
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector:
        agentpool: apppool      
      initContainers:
      # Initialize the elasticsearch directory if it doesn't exist
      - name: create-elastic-folder
        image: busybox
        command: [ "sh", "-c", "mkdir -p /data/elasticsearch && chown -R 1000:1000 /data/elasticsearch" ]
        volumeMounts:
        - name: data
          mountPath: /data
      - name: create-mongo-folder
        image: busybox
        command: [ "sh", "-c", "mkdir -p /data/mongodb /data/mongodb/db /data/mongodb/logs && chown -R 1000:1000 /data/mongodb" ]
        volumeMounts:
        - name: data
          mountPath: /data         
      containers:
      # OpenSquiggly container
      - name: opensquiggly
        image: docker.io/opensquiggly/opensquiggly:latest
        ports:
        - containerPort: 80
      # ElasticSearch container
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
        env:
        - name: discovery.type
          value: single-node
        - name: cluster.name
          value: opensquiggly
        - name: path.data
          value: /data/elasticsearch
        volumeMounts:
        - name: data
          mountPath: /data
      # MongoDB container
      - name: mongodb
        image: mongo:5.0.3
        command: [ "mongod", "--dbpath", "/data/mongodb/db", "--logpath", "/data/mongodb/logs/mongod.log" ]
        env:
          - name: MONGO_DATA_DIR
            value: /data/mongodb/db
          - name: MONGO_LOG_DIR
            value: /data/mongodb/logs
        ports:
          - containerPort: 27017
        volumeMounts:
        - name: data
          mountPath: /data     
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-azure-managed-disk