apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Release.Name }}-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: linode-block-storage-retain
  resources:
    requests:
      storage: {{ .Values.diskSize }}Gi