apiVersion: v2
name: azure-allinone
version: 1.0.0
description: A Helm chart for an all-in-one instance of OpenSquiggly with MongoDB and ElasticSearch installed as a multi-container pod, with Azure-specific options
type: application
appVersion: "1.0"
maintainers:
  - name: Kevin Dietz
    email: info@opensquiggly.com
    url: https://opensquiggly.com