diskSize: 32
useExistingPv: ""
useExistingPvc: ""
useExistingStorageClass: ""
exposeWith: LoadBalancer
dnsHostName: ""
sslCertSecret: ""
ingressClassName: nginx
storageClassProvisioner: linodebs.csi.linode.com