{{- $azureJson := dict "tenantId" .Values.tenantId "subscriptionId" .Values.subscriptionId "resourceGroup" .Values.resourceGroup "aadClientId" .Values.aadClientId "aadClientSecret" .Values.aadClientSecret -}}
{{- $jsonString := toJson $azureJson -}}
{{- $encodedJson := $jsonString | b64enc -}}
apiVersion: v1
kind: Secret
metadata:
  name: azure-dns-secret
type: Opaque
data:
  azure.json: {{ $encodedJson | quote }}